name: build dummy unikernel

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch Unikraft
        uses: actions/checkout@v4
        with:
          repository: unikraft/unikraft
          path: .unikraft/unikraft
          ref: RELEASE-0.16.3

      - name: Fetch Unikraft’s musl
        uses: actions/checkout@v4
        with:
          repository: unikraft/lib-musl
          path: .unikraft/libs/musl

      - name: Cache musl
        uses: actions/cache@v4
        with:
          path: .unikraft/build/libmusl/*.tar.gz
          key: musl

      - name: Build unikernel
        run: |
          mkdir -p .unikraft/build
          make -C .unikraft/build CONFIG_UK_BASE=$PWD/.unikraft/unikraft/ O=$PWD/.unikraft/build/ A=$PWD L=$PWD/.unikraft/libs/musl N=dummykernel C=$PWD/.config.dummykernel_qemu-x86_64 -f $PWD/.unikraft/unikraft/Makefile V=1

      - name: Log
        run: |
          find .unikraft/build -name \*.cmd | xargs head

      - name: Look up global configuration
        run: |
          cat .unikraft/build/config
