name: build dummy unikernel

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch Unikraft
        uses: actions/checkout@v4
        with:
          repository: unikraft/unikraft
          path: .unikraft/unikraft
          # ref: RELEASE-0.16.3

      - name: Fetch Unikraft’s musl
        uses: actions/checkout@v4
        with:
          repository: unikraft/lib-musl
          path: .unikraft/libs/musl

      - name: Cache musl
        uses: actions/cache@v4
        with:
          path: |
            .unikraft/build/libmusl/*.tar.gz
            .unikraft/qemu/libmusl/*.tar.gz
          key: musl

      - name: Create default build directories
        run: |
          mkdir -p .unikraft/qemu .unikraft/fc
          if [ -e .unikraft/build/libmusl ]; then mv .unikraft/build/libmusl .unikraft/qemu/; fi

      - name: Complete QEMU configuration
        run: |
          umask 0022
          make -C .unikraft/qemu CONFIG_UK_BASE=$PWD/.unikraft/unikraft/ O=$PWD/.unikraft/qemu/ A=$PWD L=$PWD/.unikraft/libs/musl N=dummykernel C=$PWD/.config.dummykernel_qemu-x86_64 -f $PWD/.unikraft/unikraft/Makefile olddefconfig V=1

      - name: Build unikernel
        run: |
          umask 0022
          make -C .unikraft/qemu CONFIG_UK_BASE=$PWD/.unikraft/unikraft/ O=$PWD/.unikraft/qemu/ A=$PWD L=$PWD/.unikraft/libs/musl N=dummykernel C=$PWD/.config.dummykernel_qemu-x86_64 -f $PWD/.unikraft/unikraft/Makefile V=1

      - name: Copy musl sources
        run: |
          mkdir -p .unikraft/fc/libmusl
          cp .unikraft/qemu/libmusl/*.tar.gz .unikraft/fc/libmusl/

      - name: Complete FC configuration
        run: |
          umask 0022
          make -C .unikraft/fc CONFIG_UK_BASE=$PWD/.unikraft/unikraft/ O=$PWD/.unikraft/fc/ A=$PWD L=$PWD/.unikraft/libs/musl N=dummykernel C=$PWD/.config.dummykernel_fc-x86_64 -f $PWD/.unikraft/unikraft/Makefile olddefconfig V=1

      - name: Build unikernel
        run: |
          umask 0022
          make -C .unikraft/fc CONFIG_UK_BASE=$PWD/.unikraft/unikraft/ O=$PWD/.unikraft/fc/ A=$PWD L=$PWD/.unikraft/libs/musl N=dummykernel C=$PWD/.config.dummykernel_fc-x86_64 -f $PWD/.unikraft/unikraft/Makefile V=1

      - name: Log
        run: |
          head .unikraft/qemu/appdummykernel.ld.o.cmd .unikraft/qemu/dummykernel_qemu-x86_64.dbg.cmd .unikraft/qemu/dummykernel_qemu-x86_64.cmd .unikraft/qemu/dummykernel_qemu-x86_64.bootinfo.cmd
          head .unikraft/fc/appdummykernel.ld.o.cmd .unikraft/fc/dummykernel_fc-x86_64.dbg.cmd .unikraft/fc/dummykernel_fc-x86_64.cmd .unikraft/fc/dummykernel_fc-x86_64.bootinfo.cmd

      - name: Look up global configurations
        run: |
          cat .config.dummykernel_qemu-x86_64
          echo ------
          cat .unikraft/qemu/config
          echo ------
          diff -u .config.dummykernel_qemu-x86_64 .unikraft/qemu/config || true
          echo ------
          cat .config.dummykernel_fc-x86_64
          echo ------
          cat .unikraft/fc/config
          echo ------
          diff -u .config.dummykernel_fc-x86_64 .unikraft/fc/config || true

      - name: Compare the builds
        run: |
          git diff --no-index .unikraft/qemu .unikraft/fc || true

      - name: Rebuild info
        run: |
          umask 0022
          make -C .unikraft/qemu CONFIG_UK_BASE=$PWD/.unikraft/unikraft/ O=$PWD/.unikraft/qemu/ A=$PWD L=$PWD/.unikraft/libs/musl N=dummykernel C=$PWD/.config.dummykernel_qemu-x86_64 -f $PWD/.unikraft/unikraft/Makefile -W dummykernel_qemu-x86_64.dbg -n V=1
