name: build dummy unikernel

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Fetch Unikraft
        uses: actions/checkout@v4
        with:
          repository: unikraft/unikraft
          path: .unikraft/unikraft
      - name: Fetch Unikraft’s musl
        uses: actions/checkout@v4
        with:
          repository: unikraft/lib-musl
          path: .unikraft/libs/musl
      - name: Link Makefile
        run: |
          make -C .unikraft/unikraft CONFIG_UK_BASE=$PWD/.unikraft/unikraft/ O=$PWD/.unikraft/build/ A=$PWD L=$PWD/.unikraft/libs/musl N=dummykernel C=$PWD/.config.dummykernel_qemu-x86_64 $PWD/.unikraft/build/Makefile V=1
      - name: Build unikernel
        run: |
          make -C .unikraft/build CONFIG_UK_BASE=$PWD/.unikraft/unikraft/ O=$PWD/.unikraft/build/ A=$PWD L=$PWD/.unikraft/libs/musl N=dummykernel C=$PWD/.config.dummykernel_qemu-x86_64 V=1
      - name: Log
        run: |
          find .unikraft/build -name \*.cmd | xargs head
